package com.rslakra.iws.bo.finance;

public enum ClaimType {
    AUTO_RENTAL_COVERAGE,
    BAGGAGE_DELAY_INSURANCE,
    EXTENDED_WARRANTY_PROTECTION,
    LOST_LUGGAGE_REIMBURSEMENT,
    PURCHASE_PROTECTION,
    ROADSIDE_ASSISTANCE,
    TRAVEL_ACCIDENT_INSURANCE,
    TRAVEL_EMERGENCY_ASSISTANCE,
    TRIP_CANCELLATION_INTERRUPTION_INSURANCE,
    ADDITIONAL_TERMS,
    ;
}
