# swagger.yml
# Author: Rohtash Lakra
#

# Default Configuration
openapi: 3.0.0
info:
  title: "An eCommerce Applications"
  description: "An eCommerce Python REST APIs With Flask"
  version: "1.0.0"

#
# Servers Configuration
# By providing "/swagger/api" as the value of url,
# you’ll be able to access all of your API paths relative to http://localhost:8000/swagger/api.
#
servers:
  - url: "/api"


#